### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by amadejkastelic** [amadejkastelic/SimpleVideoEditor#11]
Custom variable declaration on top of the editor. Call these variables later, to assign a value.

**Comment by amadejkastelic** [comment]
Variable support added. Usage example (define variables on top in `-variables:` and call them with `$variable_name`):

```yml
- variables: 
    test: test
    font_position: center
    font_size: 200
- part:
    path: /opt/projects/svpeditor/res/sample_fhd.mp4
    start: 11
    end: 15
    type: VIDEO
    audio:
      path: /opt/projects/svpeditor/res/sample.mp3
      start: 11
    text:
      - part:
          value: video test center
          position: $font_position
          size: $font_size
          font: Fira Code
          color: FFAA0000
      - part:
          value: video test bottom
          position: BOTTOM
          size: 50
          font: Fira Code
          color: FF00AAFF
```
